name: figure_the_brand
description: Figure The Brand.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # auto-update
  store_redirect: ^2.0.1
  package_info_plus: ^4.1.0

  #Database dependencies
  hive_flutter: ^1.1.0

  #Firebase
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.5

  #Network Essentials
  http: ^1.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12

  # state management
  hooks_riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1

  #utils
  intl: 
  intl_phone_number_input: ^0.7.0+2
  currency_text_input_formatter: ^2.1.5
  validators: ^3.0.0
  image_picker: ^0.8.6
  flutter_svg: ^1.1.6
  lottie: ^1.3.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.1.1
  video_player: ^2.4.7
  pinput: ^2.0.0
  pie_chart: ^5.3.2
  expandable: ^5.0.1
  smooth_page_indicator: ^1.0.0+2
  file_picker: ^5.2.4
  fluttertoast: ^8.1.2
  flutter_html: ^3.0.0-alpha.6
  money_formatter: ^0.0.3
  easy_debounce: ^2.0.2+1
  dropdown_search: ^5.0.5
  share_plus: ^4.0.10
  timeago: ^3.3.0
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.7
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.6
  hive_generator: ^1.1.2

  
flutter_native_splash:
  color: "#C0D9E5"
  #image: assets/images/japa1024.png
  ios: true
  android: true

flutter_icons:
  android: true
  ios: true
  #image_path: "assets/images/Mobile-icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700 